[package]
name = "quickwit-datetime"
description = "Date and datetime utilities for Quickwit"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
time = { workspace = true }
time-fmt = "0.3.8"
